### PR TITLE
Store geoserver styles via filesystem

### PR DESCRIPTION
**Pull request by nbrinckm**
The change here makes sure that we set the geoserver styles using the file-system.
This is the less error-prone-version that can be used with the tomcat internal geoserver.

### CODE REVIEW

**Comment by MichaelLangbein** [comment]
Getting a weird style for post-eq-damage: 

http://localhost/geoserver/wms?REQUEST=GetLegendGraphic&SERVICE=WMS&VERSION=1.1.1&FORMAT=image/png&BGCOLOR=0xFFFFFF&TRANSPARENT=TRUE&LAYER=riesgos:Shape_b466dceb-6d94-4bc8-a525-0e34825d362c8135568225139044933&STYLES=default&style=style-damagestate-sara-plasma

Screenshot from 2023-05-26 13-50-31

**Comment by MichaelLangbein** [comment]
> Getting a weird style for post-eq-damage:

Weirdly, shakyground styles are working fine. Might not have properly cleaned my volumes last time. Testing again ...

**Comment by nbrinckm** [comment]
Maybe you can check the new and the old way of storing the styles.

When the styles are send via rest api the geoserver can make some changes. In the past I think we had those, but after setting with the filesystem we lost that.
Maybe it was needed.

If the old way was better we should revert this change and to back to setting the styles via rest api

**Comment by MichaelLangbein** [comment]
> If the old way was better we should revert this change and to back to setting the styles via rest api

Yeah, it works fine with the old way of sending the styles per http request. 
Ok, let's just use the old way for now! I'll simply close this PR for now - we can reopen it if we want.

**Comment by MichaelLangbein** [comment]
> When the styles are send via rest api the geoserver can make some changes. In the past I think we had those, but after setting with the filesystem we lost that.

That's quite an interesting observation, btw. I remember that geoserver has a few ideosyncracies when it comes to sld's, maybe this is another example of that.

**Pull request closed without merging**
